builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/sapcc/go-api-declarations/bininfo.binName=ntp_exporter
      - -X github.com/sapcc/go-api-declarations/bininfo.version={{ .Version }}
      - -X github.com/sapcc/go-api-declarations/bininfo.commit={{ .FullCommit  }}
      # Use CommitDate instead of Date for reproducibility.
      - -X github.com/sapcc/go-api-declarations/bininfo.buildDate={{ .CommitDate }}
    # Set the modified timestamp on the output binary to ensure that builds are reproducible.
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - name_template: '{{ .ProjectName }}-{{ replace .Version "v" "" }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"
